dist:     xenial
sudo:     required

language: c

os: linux

compiler: gcc

env:
  global:
  - CODECOV_TOKEN="58d4334d-2d8d-43b8-b384-2257c6456405"

install:
  - sudo apt-get update
  - sudo apt-get install valgrind
  - sudo apt-get install libstdc++6
  - sudo apt-get install cmake
  - sudo apt-get install lcov
  #  - sudo apt-get install gcov
  #  - sudo apt-get install gcovr
  - sudo apt-get install clang
  - sudo apt-get install clang-format

before_script:

  - clang-format -i -style=Google *.h *.c
  - ./linters/run.sh || travis_terminate 1

script:

  - cmake . #-fprofile-arcs -ftest-coverage .
  - cmake --build . || travis_terminate 1
  #- gcovr -r . #so here i can see test summary on travis site
  #    - ctest .
  - valgrind --tool=memcheck --gen-suppressions=all --leak-check=full --leak-resolution=med --track-origins=yes --vgdb=no ./a.out < in.txt

after_script:

  - lcov —capture —directory ./CMakeFiles/task_library.dir/project/src —output-file coverage.info
  - bash <(curl -s https://codecov.io/bash)
  - make clean